server:
  port: 8888

spring:
  application:
    name: redis-service
  #redis配置
  redis:
    host: localhost   #redis配置id
    port: 6379
    password: 123456
    #采用lettuce方式连接
    lettuce:
      shutdown-timeout: 100s # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30s # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

###开启Hystrix断路器
feign:
  hystrix:
    enabled: true
###配置请求超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
    ###配置具体方法超时时间
#    serverMethod:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000